### ISSUE TITLE
OOP-1-review-2022-10-15

### ISSUE THREAD

**Issue by hamerlinski** [szarrk/oop-put-course#1]
**Task 1**
- [ ] Remove comment from lines 1--4
- [ ] Rename file to something like exercise1 instead of zadanie1
- [ ] Proper communication/interaction between classes and objects could be solved better

**Task 2**
- [ ] Rename file to something like exercise2 instead of zadanie2
